export const miragePositions = {
    ctSmoke: "CT",
    aSiteSmoke: "A Site",
    jungleSmoke: "Jungle",
    stairsSmoke: "Stairs",
    connectorUpSmoke: "Upper Connector",
    jungleDeepSmoke: "Jungle Deep",
    connectorDownSmoke: "Down Connector",
    windowSmoke: "Mid Window",
    catwalkSmoke: "Short",
    midCatwalkSmoke: "Catwalk",
    topMidSmoke: "Top Mid",
    exitSmoke: "Exit",
    bWindowSmoke: "B Window",
    shortLeftSmoke: "B Left Short",
    shortRightSmoke: "B Right Short",
    bSiteOneSmoke: "B Site Standard",
    bSiteTwoSmoke: "B Site Between One and Two Box",
    bSiteThreeSmoke: "B Site Between Two and Three Box",
    bSiteFourSmoke: "B Site Between Three and Four Box",
    bBenchSmoke: "B Bench",
    bBalconySmoke: "B Balcony",

    ctFlash: "CT",
    aSiteFlash: "A Site",
    jungleFlash: "Jungle",
    stairsFlash: "Stairs",
    connectorDownFlash: "Down Connector",
    catwalkFlash: "Catwalk",
    topMidFlash: "Top Mid",
    bSiteFlash: "B Site",
    overAFlash: "A Over",
    overBFlash: "B Over",
    windowFlash: "Window",

    underWoodMolotov: "Under Wood",
    aBenchMolotov: "A Bench",
    carMolotov: "Car",
    bBalconyMolotov: "B Balcony",
    underAppsMolotov: "Under Apartments",
    windowMolotov: "Window",
    ladderMolotov: "Ladder Room",
    ninjaMolotov: "Ninja",
    sandwichMolotov: "Sandwich",
    fireboxMolotov: "Firebox",
}