export const miragePositions = {
    ctSmoke: "CT",
    aSiteSmoke: "A Site",
    jungleSmoke: "Jungle",
    stairsSmoke: "Stairs",
    connectorUpSmoke: "Upper Connector",
    jungleDeepSmoke: "Jungle Deep",
    connectorDownSmoke: "Down Connector",
    windowSmoke: "Mid Window",
    catwalkSmoke: "Short",
    midCatwalkSmoke: "Catwalk",
    topMidSmoke: "Top Mid",
    exitSmoke: "Exit",
    bWindowSmoke: "B Window",
    shortLeftSmoke: "B Left Short",
    shortRightSmoke: "B Right Short",
    bSiteOneSmoke: "B Site Standard",
    bSiteTwoSmoke: "B Site Between One and Two Box",
    bSiteThreeSmoke: "B Site Between Two and Three Box",
    bSiteFourSmoke: "B Site Between Three and Four Box",
    bBenchSmoke: "B Bench",
    bBalconySmoke: "B Balcony",
    bTrashCanSmoke: "B Trash Can",
    bSiteCornerSmoke: "B Site Corner",
    bAppsSmoke: "B Apps",
    bAppsDeepSmoke: "B Apps Deep",
    bShortDeepSmoke: "B Short Deep",
    deepTopMidSmoke: "Deep Top Mid",
    aRampSmoke: "A Ramp",
    aRampDeepSmoke: "A Ramp Deep",
    tetrisSmoke: "Tetris",
    aPalaceSmoke: "A Palace",
    aFireboxSmoke: "A Firebox",
    aDefaultSmoke: "A Default",

    ctFlash: "CT",
    aSiteFlash: "A Site",
    jungleFlash: "Jungle",
    stairsFlash: "Stairs",
    connectorDownFlash: "Down Connector",
    catwalkFlash: "Catwalk",
    topMidFlash: "Top Mid",
    bSiteFlash: "B Site",
    overAFlash: "A Over",
    overBFlash: "B Over",
    windowFlash: "Window",
    bAppsFlash: "B Apps",
    ladderFlash: "Ladder Room",
    behindMidBoxesFlash: "Behind Mid Boxes",
    rampFlash: "Ramp",
    rampDeepFlash: "Ramp Deep",
    palaceFlash: "Palace",

    underWoodMolotov: "Under Wood",
    aBenchMolotov: "A Bench",
    carMolotov: "Car",
    bBalconyMolotov: "B Balcony",
    underAppsMolotov: "Under Apartments",
    windowMolotov: "Window",
    ladderMolotov: "Ladder Room",
    ninjaMolotov: "Ninja",
    sandwichMolotov: "Sandwich",
    fireboxMolotov: "Firebox",
    bAppsDeepMolotov: "B Apps Deep",
    topMidBoxesMolotov: "Top Mid Boxes",
    aRampMolotov: "A Ramp",
    aRampDeepMolotov: "A Ramp Deep",
    palaceMolotov: "Palace",
    ctMolotov: "CT",
    jungleMolotov: "Jungle",
    kitchenMolotov: "Kitchen",
}

export const infernoPositions = {
    bCTSmoke: "B CT",
    bSpoolsSmoke: "Spools",
    bSiteSmoke: "B Site",
    bCTDeepSmoke: "CT Very Deep",
    topBananaSmoke: "Top Banana",
    topMidSmoke: "Top Mid",
    midLongSmoke: "Long",
    midShortSmoke: "Short",
    connectorSmoke: "Connector",
    farLongSmoke: "Far Long",
    librarySmoke: "Library",
    behindASiteSmoke: "Behind A Site",
    graveyardSmoke: "Graveyard",
    truckSmoke: "Truck",
    miniPitSmoke: "Mini Pit",
    pitSmoke: "Pit",

    bCTFlash: "B CT",
    bEntranceFlash: "B Entrance",
    topBananaFlash: "Top Banana",
    bSiteFlash: "B Site",
    topMidFlash: "Top Mid",
    longFlash: "Long",
    aAppsFlash: "Apps",
    aSiteFlash: "A Site",

    bCarMolotov: "Car",
    bFirstBoxMolotov: "First Box",
    bSecondBoxMolotov: "Second Box",
    bThirdBoxMolotov: "Third Box",
    bDarkMolotov: "Dark",
    bSpoolsMolotov: "Spools",
    longMolotov: "Long",
    appsMolotov: "Apps",
    roofMolotov: "Roof",
    miniPitMolotov: "Mini Pit",
    pitMolotov: "Pit",
}
export const overpassPositions = {
    aBankSmoke: "Bank",
    aVanSmoke: "Van",
    aSiteSmoke: "A Site",
    stairsSmoke: "Stairs",
    truckSmoke: "Truck",
    heavenSmoke: "Heaven",
    abcSmoke: "ABC",
    bridgeSmoke: "Bridge",
    bSiteSmoke: "B Site",
    squeakySmoke: "Squeaky",
    bananaSmoke: "Banana",
    bathroomSmoke: "Bathroom",
    connectorSmoke: "Connector",

    midFlash: "Mid",
    longFlash: "Long",
    aSiteFlash: "A Site",
    aSiteLongFlash: "A Site Long",
    monsterFlash: "Monster",
    shortFlash: "Short",
    bSiteFlash: "B Site",

    aSiteMolotov: "A Site",
    truckMolotov: "Truck",
    heavenMolotov: "Heaven",
    pitMolotov: "Pit",
    bSiteMolotov: "B Site",
    waterMolotov: "Water",
    barrelsMolotov: "Barrels",
    sandbagsMolotov: "Sandbags",
}
export const ancientPositions = {
    platformSmoke: "Platform",
    templeSmoke: "Temple",
    aSiteSmoke: "A Site",
    aCTSmoke: "A CT",
    donutSmoke: "Donut",
    windowSmoke: "Window",
    tombSmoke: "Tomb",
    heavenSmoke: "Heaven/Catwalk",
    caveSmoke: "Cave",
    caveBSiteSmoke: "B Site",
    bShortSmoke: "B Short",
    bLongSmoke: "B Long",
    bAlleySmoke: "B Alley",
    houseSmoke: "House",

    aEntranceFlash: "A Entrance",
    aSiteFlash: "A Site",
    midFirstFlash: "Mid Left",
    midSecondFlash: "Mid Right",
    caveFlash: "Cave",
    bSiteFlash: "B Site",
    windowFlash: "Window",
    longFlash: "Long",

    cubbyMolotov: "Cubby",
    behindASiteMolotov: "Behind A Site",
    templeMolotov: "Temple",
    platformMolotov: "Platform",
    wideBoxMolotov: "Wide Box",
    windowMolotov: "Window",
    ninjaMolotov: "Ninja",
    bSiteMolotov: "B Site",
    longMolotov: "Long",
}
export const nukePositions = {
    heavenSmoke: "Heaven",
    outsideHeavenSmoke: "Outside Heaven",
    lockerSmoke: "Locker",
    ventSmoke: "Vent T",
    mainSmoke: "Main",
    outsideMainSmoke: "Outside Main",
    outsideSecretSmoke: "Outside Secret Cross",
    garageSmoke: "Garage",
    outsideRedSmoke: "Outside Red 1/2",
    outsideRedSecretSmoke: "Outside Red Secret Cross",
    underHeavenSmoke: "Under Heaven",
    bAquariumSmoke: "Aquarium",
    bDoubleDoorsSmoke: "B Double Doors",
    bSingleDoorSmoke: "B Door",

    outsideFlash: "Outside",
    aSiteFlash: "A Site",
    rampFlash: "Ramp",
    mainFlash: "Main",

    hutRoofMolotov: "Hut Roof",
    aSiteMolotov: "A Site",
    heavenMolotov: "Heaven",
    ctVentMolotov: "Vent CT",
    redMolotov: "Red",
    secretMolotov: "Secret",
    rampBoxMolotov: "Ramp Box",
    darkMolotov: "B Dark",
    bSiteMolotov: "B Site",
}
export const vertigoPositions = {
    generatorSmoke: "Generator",
    generatorLeftSmoke: "Generator Left",
    bCTSmoke: "B CT",
    windowSmoke: "Window / Boost",
    midElevatorSmoke: "Mid Elevator",
    aElevatorSmoke: "A Elevator",
    aSiteSmoke: "A Site",
    aSiteLeftSmoke: "A Site Left",
    aSiteRightSmoke: "A Site Right",
    headshotSmoke: "Headshot",
    heavenSmoke: "Heaven",
    aCTSmoke: "A CT",
    gapSmoke: "Gap",

    bSiteFlash: "B Site",
    windowFlash: "Window / Boost",
    bStairsFlash: "B Stairs",
    midFlash: "Mid",
    gapFlash: "Gap",
    rampFlash: "Upper Ramp",
    aSiteFlash: "A Site",

    bSiteMolotov: "B Site",
    tetrisMolotov: "Tetris",
    bCornerMolotov: "B Corner",
    windowMolotov: "Window / Boost",
    ctSpawnMolotov: "CT Spawn",
    elevatorMidMolotov: "Mid Elevator",
    gapMolotov: "Gap",
    sidewalkMolotov: "Sidewalk",
    headshotMolotov: "Headshot",
    heavenMolotov: "Heaven",
}
export const anubisPositions = {
    streetSmoke: "Street",
    palaceSmoke: "Palace",
    bSiteSmoke: "B Site",
    backsiteBSmoke: "B Backsite",
    connectorUpSmoke: "Upper Connector",
    connectorDownSmoke: "Lower Connector",
    bridgeSmoke: "Bridge",
    windowSmoke: "Window",
    midPalaceSmoke: "Mid Palace",
    walkwaySmoke: "Walkway",
    heavenSmoke: "Heaven",
    platformSmoke: "Platform",
    aStairsSmoke: "A Stairs",
    aMainSmoke: "A Main",

    bSiteFlash: "B Site",
    bEntranceFlash: "B Entrance",
    bridgeFlash: "Bridge",
    canalsFlash: "Canals",
    connectorFlash: "Connector",
    aMainFlash: "A Main",
    aSiteFlash: "A Site",

    bPillarMolotov: "B Pillar",
    bBacksiteMolotov: "B Backsite",
    ninjaMolotov: "Ninja",
    palaceMolotov: "Palace",
    windowMolotov: "Window",
    doubleDoorsMolotov: "Double Doors",
    walkwayMolotov: "Walkway",
    platformMolotov: "Platform",
    aStairsMolotov: "A Stairs",
    aSiteMolotov: "A Site",
    heavenMolotov: "Heaven",
    fountainMolotov: "Fountain",
}